name: Cypress Tests

on:
  schedule:
    - cron: '40 15 * * *'  # Runs daily at 3:40 PM UTC
  push:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        
          
 
       